### ISSUE TITLE
doesn't sort by the zipcode

### ISSUE THREAD

**Issue by tech18** [awatson1978/minimongo-table#2]
Hello Abigail,

I have implemented this in one of the collections which also has a zipcode. In zipcode column I'm only storing numbers, so how can I sort/search by only "numbers" column?

Looking forward for your quick reply.

Cheers
Sunil Jain

**Comment by awatson1978** [comment]
Hi Sunil,
That functionality isn't implemented.  You'll probably want to edit `customersList` helper, and add a sort field to the query's options object.  It look something like this:

``` js
{
  limit: Session.get('tableLimit'),
  skip: Session.get('skipCount'),
  sort: {Zip: 1}    
}
```

See this file:
https://github.com/awatson1978/minimongo-table/blob/master/webapp/client/miniMongoTable/miniMongoTable.js#L71-74

Best of luck.

**Comment by tech18** [comment]
Thanks for the reply.

When it comes to searching, regex doesn't support numerical values as it works only for strings. I searched for resources and found using $where can help or $type with $regex can yield the required search on zipcode. Any help from your side on this would be greatly appreciated.

Thanks in advance.

Cheers
Sunil Jain
